### ISSUE TITLE
I did not find the modality "sentence" in https://zenodo.org/records/11167750，in participant_metadata.csv.Is this URL correct?

### ISSUE THREAD

**Issue by 0nem0relight** [alan-turing-institute/Turing-RSS-Health-Data-Lab-Biomedical-Acoustic-Markers#13]

**Comment by 0nem0relight** [comment]
![image](https://github.com/user-attachments/assets/ca97ffcf-3f0c-40e8-acda-da117fd47697)
is that correct?

**Comment by harrygcoppock** [comment]
Hey! Yes, unfortunately the sentence modality was classified as 'personally identifiable data' and therefore is not available in the open source version of the dataset. The cough, three cough and exhalation is though.

You can apply to access the full dataset through a data sharing contract (see NMI paper for more details) however you need to be a UK academic institution.

Best,
Harry

**Comment by 0nem0relight** [comment]
another question 
![image](https://github.com/user-attachments/assets/4b4ab100-27d6-4c97-ab2f-758bcf2a382e)
how to calculate the following characteristic metrics:exhalation_amplitude,exhalation_signal_mean_std_ratio,especially,exhalation_signal_mean_std_ratio?

**Comment by 0nem0relight** [comment]
Another question:
I noticed that all experiments were based on mel spectrogram.Is it possible for Mel spectrogram to have flaws in detecting COVID-19 or something else?
